github.com:
    users:
        zokz9:
            oauth_token: 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
    git_protocol: ssh
    user: zokz9
    oauth_token: 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
