runtime:
  threads: null
release:
  check: true
manifest:
  enable: false
  secondary:
    - url: https://cdn.losbroxas.org/manifest.yaml
      enable: true
language: en-US
theme: light
roots:
  - store: steam
    path: /home/zokz/.local/share/Steam
redirects: []
backup:
  path: /home/zokz/ludusavi-backup
  ignoredGames: []
  filter:
    excludeStoreScreenshots: false
    cloud:
      exclude: false
      epic: false
      gog: false
      origin: false
      steam: false
      uplay: false
    ignoredPaths: []
    ignoredRegistry: []
  toggledPaths: {}
  toggledRegistry: {}
  sort:
    key: status
    reversed: false
  retention:
    full: 1
    differential: 0
  format:
    chosen: simple
    zip:
      compression: deflate
    compression:
      deflate:
        level: 6
      bzip2:
        level: 6
      zstd:
        level: 10
  onlyConstructive: false
restore:
  path: /home/zokz/ludusavi-backup
  ignoredGames: []
  toggledPaths: {}
  toggledRegistry: {}
  sort:
    key: status
    reversed: false
  reverseRedirects: false
scan:
  showDeselectedGames: true
  showUnchangedGames: true
  showUnscannedGames: true
cloud:
  remote: null
  path: ludusavi-backup
  synchronize: true
apps:
  rclone:
    path: ""
    arguments: --fast-list --ignore-checksum
customGames: []
